/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.utils.UserServiceUtil;

import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc=new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;
        try {
            userBookingService=new UserBookingService();
        }
        catch (IOException e){
            System.out.println("There is something wrong");
            return;
        }
        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Train");
            System.out.println("5. Book a Ticket");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the app");
            option=sc.nextInt();
            Train trainSelectedForBooking = new Train();
            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignup=sc.next();
                    System.out.println("Enter the password");
                    String signupPass=sc.next();
                    User user=new User(nameToSignup,signupPass, UserServiceUtil.hashPassword(signupPass),new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUpUser(user);
                    break;
                case 2:
                    System.out.println("enter username to Login");
                    String nameToLogin=sc.next();
                    System.out.println("Enter the password");
                    String loginPass=sc.next();
                    User userToLogin=new User(nameToLogin,loginPass,UserServiceUtil.hashPassword(loginPass),new ArrayList<>(),UUID.randomUUID().toString());
                    try {
                        userBookingService=new UserBookingService(userToLogin);
                    }
                    catch (IOException e){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your Bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your Source Station");
                    String src=sc.next();
                    System.out.println("Type your destination station");
                    String destination=sc.next();
                    List<Train>trains=userBookingService.getTrains(src,destination);
                    int index=1;
                    for(Train t:trains){
                        System.out.println(index+" Train id : "+t.getTrainId());
                        for(Map.Entry<String,String>entry:t.getStationTimes().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelectedForBooking=trains.get(sc.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>>seats=userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer>row:seats){
                        for(Integer val:row){
                            System.out.println(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by Typing the row and column");
                    System.out.println("Enter the row");
                    int row=sc.nextInt();
                    System.out.println("Enter the column");
                    int col=sc.nextInt();
                    System.out.println("Booking your seat...");
                    Boolean booked=userBookingService.bookTrainSeat(trainSelectedForBooking,row,col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy Your journey");
                    }
                    else{
                        System.out.println("Can't book this seat");
                    }
                    break;
                default:
                    break;
            }
        }
    }
}
